import Theme from "@/components/Theme";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={Theme}>
      <CssBaseline />
      <Container maxWidth="lg">
        {/* Your layout components go here */}
        {children}
      </Container>
    </ThemeProvider>
  );
}
